version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: MyDb123@abc
    networks:
      - hakan-net
    
  myapp:
    image: hakan/bookstore_api:latest
    container_name: myapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - hakan-net
    
networks:
    hakan-net:
      driver: bridge